Upload dataset from .csv local file

Read .csv file into a pandas dataframe

In [1]:
import pandas as pd
df = pd.read_csv("./supports/har_dataset_preprocessedScaled.csv")
data = pd.read_csv("./supports/S2.csv")

Divide df into train and test (Training Sample)

In [4]:
from sklearn.model_selection import train_test_split
df.reset_index()
y = df["target"] 
X = df.drop(columns="target")
X_train, X_rem, y_train, y_rem = train_test_split(X, y, random_state=42, test_size=0.20, shuffle=True)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem,random_state=42, test_size=0.5)


Train Random Forest Model


In [5]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators= 1800, min_samples_split= 2, min_samples_leaf= 4, max_features='auto', max_depth= 50, bootstrap=False)
rf.fit(X_train,y_train)

C:\Users\simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(bootstrap=False, max_depth=50, max_features='auto',
                       min_samples_leaf=4, n_estimators=1800)

In [32]:
from sklearn.metrics import mean_squared_error,r2_score
from sklearn import metrics
predictions = rf.predict(X_test)

from pprint import pprint
# arr is the numpy ndarray
#pprint(predictions.tolist())
print(predictions)

print(r2_score(y_test, predictions))
print("Evaluating the Algorithm:\n")
print(metrics.confusion_matrix(y_test, predictions))
print(metrics.classification_report(y_test, predictions))


print("Evaluating Prediction Accuracy:\n")
print("Accuracy:", metrics.accuracy_score(y_test, predictions))


[0. 1. 0. ... 0. 1. 1.]
0.5925957207207206
Evaluating the Algorithm:

[[892  68]
 [135 901]]
              precision    recall  f1-score   support

         0.0       0.87      0.93      0.90       960
         1.0       0.93      0.87      0.90      1036

    accuracy                           0.90      1996
   macro avg       0.90      0.90      0.90      1996
weighted avg       0.90      0.90      0.90      1996

Evaluating Prediction Accuracy:

Accuracy: 0.8982965931863728


In [33]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
data = data[(data['userTarget'] == 0) | (data['userTarget'] == 1)] 

y = data['userTarget']
X = data.drop(['userTarget'],axis=1);


predictions = rf.predict(X)

from pprint import pprint
# arr is the numpy ndarray
#pprint(predictions.tolist())
print(predictions)

print(r2_score(y, predictions))
print("Evaluating the Algorithm:\n")
print(metrics.confusion_matrix(y, predictions))
print(metrics.classification_report(y, predictions))


print("Evaluating Prediction Accuracy:\n")
print("Accuracy:", metrics.accuracy_score(y, predictions))


       android.sensor.accelerometer#mean  android.sensor.accelerometer#min  \
0                               0.959836                          0.792872   
1                               0.961322                          0.949409   
2                               0.101856                          0.100376   
3                               0.118582                          0.113220   
4                               0.992690                          0.978262   
...                                  ...                               ...   
19951                           0.101044                          0.100857   
19952                           0.954418                          0.954420   
19953                           0.142576                          0.142552   
19954                           0.107256                          0.107231   
19955                           0.158915                          0.158891   

       android.sensor.accelerometer#max  android.sensor.acceler

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- accelometer#max
- accelometer#mean
- accelometer#min
- accelometer#std
- gyroscope#max
- ...
Feature names seen at fit time, yet now missing:
- android.sensor.accelerometer#max
- android.sensor.accelerometer#mean
- android.sensor.accelerometer#min
- android.sensor.accelerometer#std
- android.sensor.gyroscope#max
- ...

  warnings.warn(message, FutureWarning)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-2.1666666666666665
Evaluating the Algorithm:

[[ 0 13]
 [ 0  6]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.32      1.00      0.48         6

    accuracy                           0.32        19
   macro avg       0.16      0.50      0.24        19
weighted avg       0.10      0.32      0.15        19

Evaluating Prediction Accuracy:

Accuracy: 0.3157894736842105


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [6]:
from sklite import LazyExport
lazy = LazyExport(rf)
lazy.save('test.json')

C:\Users\simon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklite\lib\abstract.py:85: UserWarning: C:\Users\simon/.sklite has been created.
  warnings.warn(wrn)


In [8]:
print(rf.get_params(deep=True))

{'bootstrap': False, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 50, 'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 4, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 1800, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}
